# Generated by Django 4.0.4 on 2022-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laboratory_Name', models.CharField(max_length=20)),
                ('LabStatus', models.CharField(max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
