# Generated by Django 4.0.4 on 2022-05-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_addlab_delete_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlab',
            name='Floor_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlab',
            name='LabCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlab',
            name='Laboratory_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlab',
            name='Laboratory_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlab',
            name='NumOfChairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addlab',
            name='NumOfPcs',
            field=models.IntegerField(default=0),
        ),
    ]
