# Generated by Django 4.0.4 on 2022-05-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_addlab_floor_number_addlab_labcapacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlab',
            name='LabStatus',
            field=models.CharField(default=0, max_length=18),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Laboratory_Name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
