# Generated by Django 4.0.4 on 2022-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_addlab_labstatus_alter_addlab_laboratory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlab',
            name='Floor_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='LabCapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='LabStatus',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Laboratory_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Laboratory_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Laboratory_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='NumOfChairs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='NumOfPcs',
            field=models.IntegerField(null=True),
        ),
    ]
