# Generated by Django 4.0.4 on 2022-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_addlab_floor_number_alter_addlab_labcapacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laboratory_ID', models.IntegerField(null=True)),
                ('PcNum', models.IntegerField(null=True)),
                ('ProblemType', models.CharField(blank=True, choices=[('Software', 'software'), ('Hardware', 'hardware')], max_length=20, null=True)),
                ('Date', models.DateField()),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Floor_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='LabCapacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='LabStatus',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Laboratory_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Laboratory_Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='Laboratory_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='NumOfChairs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addlab',
            name='NumOfPcs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
