# Generated by Django 4.0.4 on 2022-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_report_alter_addlab_floor_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PC_ID', models.IntegerField(blank=True, null=True)),
                ('Lab_ID', models.IntegerField(blank=True, null=True)),
                ('PCStatus', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='Laboratory_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='PcNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
