# Generated by Django 4.0.4 on 2022-05-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_addnewpc_alter_report_laboratory_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportInfo',
        ),
    ]
