# Generated by Django 4.0.4 on 2022-05-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_report_reportinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlab',
            name='LabStatus',
        ),
    ]
