# Generated by Django 4.0.4 on 2022-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_addlab_labstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlab',
            name='LabStatus',
            field=models.TextField(blank=True, choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance')], max_length=18, null=True),
        ),
    ]
