# Generated by Django 4.0.4 on 2022-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_addlab_labstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlab',
            name='LabStatus',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
